Password recovery
CodeCollaborate/EclipsePlugin pull request #10
Opened 2016-11-26 06:02 UTC by fahslaj

2016-11-29 02:51 UTC, jshap70 commented
I think we need to change this to require them to send the request from the email that the account is registered under. That should eliminate the extra step on our end of verifying that they actually wanted to send the request.

2016-11-29 19:28 UTC, fahslaj commented
It has been updated to a mailto link.

2016-11-29 19:29 UTC, fahslaj commented
I've noticed that the ClientCore.jar files from this branch and the test branch are inconsistent. This branch's jar file I manually rebuilt from the test branch, so I'm a little confused. Once the other changes in this PR are approved, I'll investigate this and fix the problem.

2016-11-30 04:10 UTC, julie-is-late requested changes

2016-11-30 04:10 UTC, jshap70 commented on src/main/java/cceclipseplugin/util/OSUtil.java
> +		return getOSType().indexOf("nux") >= 0;
does mac return `Unix` in it's name? if it does, this would cause an issue.

2016-11-30 04:10 UTC, jshap70 commented on src/main/java/cceclipseplugin/ui/dialogs/RecoverPasswordDialog.java
> +			if (OSUtil.isWindows()) {
there has to be a library to automatically know how to open it

2016-11-30 04:10 UTC, jshap70 commented on src/main/java/cceclipseplugin/ui/dialogs/RecoverPasswordDialog.java
> +					Runtime.getRuntime().exec("xdg-open " + mailTo);
note that xdg-open is not the only unix open command available. this is what the zsh `open_command` helper script looks like:
```bash
case "$OSTYPE" in
	(darwin*) open_cmd='open'  ;;
	(cygwin*) open_cmd='cygstart'  ;;
	(linux*) open_cmd='xdg-open'  ;;
	(msys*) open_cmd='start ""'  ;;
	(*) echo "Platform $OSTYPE not supported"
		return 1 ;;
esac
```

2016-11-30 04:16 UTC, fahslaj commented on src/main/java/cceclipseplugin/util/OSUtil.java
> +		return getOSType().indexOf("nux") >= 0;
it does not.

2016-11-30 04:17 UTC, fahslaj commented on src/main/java/cceclipseplugin/ui/dialogs/RecoverPasswordDialog.java
> +			if (OSUtil.isWindows()) {
There probably is, but this was such a small use case that I didn't see the need to find a library. However, If you think it is necessary, I'll go ahead and find one and implement it through that.

2016-11-30 04:17 UTC, fahslaj commented on src/main/java/cceclipseplugin/ui/dialogs/RecoverPasswordDialog.java
> +					Runtime.getRuntime().exec("xdg-open " + mailTo);
yeah, i saw this. Everywhere I looked online pointed to xdg-open as being the most reliable and commonly used in unix systems.

2016-12-01 02:24 UTC, julie-is-late approved these changes

2016-12-01 02:25 UTC, jshap70 commented
Looks good, maybe just add one last quick todo about looking into other linux flavors' launchers and it LGTM

2016-12-01 02:36 UTC, merged