Sync fix
CodeCollaborate/EclipsePlugin pull request #32
Opened 2017-01-07 01:27 UTC by ObsessiveOrange

2017-01-09 17:31 UTC, fahslaj requested changes

2017-01-09 17:31 UTC, fahslaj commented on src/main/java/cceclipseplugin/editor/DocumentManager.java
>  	 * @return The queue of diffs that was applied.
You removed the Queue, so is this JavaDoc looks to be out of date.

2017-01-09 17:31 UTC, fahslaj commented on src/main/java/cceclipseplugin/editor/DocumentManager.java
> +//		}
Why is all of this code commented out? Where did this logic go?

2017-01-09 17:31 UTC, fahslaj commented on src/main/java/cceclipseplugin/editor/listeners/DocumentChangeListener.java
> +						continue diffLoop;
`docMgr.getAppliedDiffs` is called 4 times in the last 10 lines. Capture the applied diffs in a local variable right before the synchronized block.

2017-01-09 20:14 UTC, ObsessiveOrange commented on src/main/java/cceclipseplugin/editor/DocumentManager.java
> +//		}
That logic was outdated; I'm commenting it out as a reminder to build the patch reordering. Right now we're simply assuming it comes in order.

2017-01-09 20:27 UTC, ObsessiveOrange commented on src/main/java/cceclipseplugin/editor/listeners/DocumentChangeListener.java
> +						continue diffLoop;
done

2017-01-09 20:27 UTC, ObsessiveOrange commented on src/main/java/cceclipseplugin/editor/DocumentManager.java
>  	 * @return The queue of diffs that was applied.
Not really. I've put it into a hashmap, and used a linkedlist instead, but in all reality, it's a queue. I just needed access to all the methods of the linkedlist.

2017-01-10 18:39 UTC, fahslaj submitted a review, later dismissed

2017-01-15 21:00 UTC, jshap70 commented on src/main/java/cceclipseplugin/core/PluginManager.java
> +	final private String WS_ADDRESS = "ws://cody.csse.rose-hulman.edu:8000/ws/";
revert this back to use prod

2017-01-18 17:59 UTC, julie-is-late approved these changes

2017-01-18 21:08 UTC, merged